apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  template:
    spec:
      runtimeClassName: nvidia
      volumes:
      - name: kubelet-device-plugins-dir
        hostPath:
          path: /var/lib/rancher/k3s/agent/kubelet/device-plugins
          type: Directory
