apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inference
resources:
- namespace.yaml
- configmap.yaml
- storage.yaml
- headless-service.yaml
- statefulset.yaml
- service.yaml
- metrics-service.yaml
patches:
- path: runtime-class-patch.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: vllm
